#FROM python:3.9-slim
FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt update
#RUN apt install -y wget
#RUN apt install -y --fix-missing g++

COPY app.py .
RUN mkdir static
#RUN mv spinner.css static/

COPY settings.py .
COPY tlc.py .
COPY sir_numpy_c.py .
COPY sir_numpy.py .
COPY sir_sql.py .
COPY report.py .
COPY update_ages.cpp .
RUN g++ -shared -fPIC -O3 -march=native -flto -fpermissive update_ages.cpp -o update_ages.so
ADD model_numpy/ model_numpy/eula.py
ADD model_sql/ model_sql/eula.py
COPY post_proc.py .

COPY fits.npy .

CMD ["python", "app.py"]

